### ISSUE TITLE
Add Type Definitions for Typescript

### ISSUE THREAD

**Issue by diana-wang** [AlaskaAirlines/ods-button#50]
**Is your feature request related to a problem? Please describe.**
Using ods-button in a React project that uses typescript creates errors as the component is not typed but the compiler expects it to be (Specific Error: "Property 'ods-button' does not exist on type 'JSX.IntrinsicElements'")

**Describe the solution you'd like**
Add support for typescript users for this component by adding type definition files (.d.ts). This would also require importing the typescript package and using a tsconfig.

**Describe alternatives you've considered**
An alternative would be to declare the types in the consumer project, rather than in the component (as shown in this [stackoverflow](https://stackoverflow.com/questions/55424417/typescript-error-property-does-not-exist-on-type-jsx-intrinsicelements-when) post), but every consumer using typing with React would have to do that. Adding type definitions in the component would fix the issue for everyone.

I'd be glad to help implement these changes and make a PR into the project.

**Comment by diana-wang** [comment]
Alternatively, it may be better to create an npm project with types (like @types/react) that can be imported as needed?

**Comment by blackfalcon** [comment]
I am open to this discussion, but I am of two minds. I see where the opportunity is to make use easier by teams that use Typescript, but I am also of the opinion that the web component should be agnostic of all frameworks, even Typescript and feel that this is the responsibility of the consumer to address.

**Comment by diana-wang** [comment]
Hmm, that's a fair point. 

[This article](https://wespeter.com/posts/consuming-web-component-react-typescript/) goes in depth into using web components in react + typescript apps. It states that even if we did try to put types in the component, it would likely require an import of the @types/react package anyway, which shouldn't belong in the component anyway.

I'll need to do some more experimentation, but based on this, unless there's a way to put it into some sort of small types package, it may better just to put it on the consumer.

**Comment by blackfalcon** [comment]
Reading the article, I see no reason why components cannot support the .d.ts file (option 2). This does not create an awkward dependency and is simply a resource devs can pull to support TS.

**Comment by blackfalcon** [comment]
@diana-wang has there been any movement on this issue? Is this an item we need to persist?

**Comment by diana-wang** [comment]
I honestly haven’t had the time to look at it since. Feel free to close it, and I will create a PR if needed in the future.

**Comment by blackfalcon** [comment]
I am going to leave this open, but put it at the bottom of the backlog and maybe revisit later.

**Comment by blackfalcon** [comment]
There doesn't seem to be much movement on this issue and it's not part of the core Auro roadmap. 

I am electing to close this issue and of the issue comes up again, we can re-open.
