### ISSUE TITLE
Button to support 'disabled' state

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/ods-button#57]
## Is your feature request related to a problem? Please describe.

There are multiple use cases in which there is a need for a disabled and active button state to restrict a user's interaction. 

We need a designed 'disabled state' and 'active state' solution that is distinctive from the main auro-button that restricts a user's ability to interact with the form function within the view.  

## Describe the solution you'd like

A new design element that addresses this need and is distinctive from the standard auro-button.

## Describe alternatives you've considered

None

## Additional context

None

This story supports https://github.com/AlaskaAirlines/auro_docs/issues/60

**Comment by blackfalcon** [comment]
@vidalmenAS I am assuming that this issue is rescoped to only be the DISABLED state? 

Can you also add a link to the design asset?

**Comment by vidalmenAS** [comment]
https://app.abstract.com/projects/3b79fe3f-3a67-4df4-a60c-1d1174583a94/branches/master/files/b92430dd-2f01-438c-a1b9-1b4fc647cecc

**Comment by geoffrey1218** [comment]
Is there any timeline for when this feature will be added? My team had to revert back to using ods-button so we could use the disabled state.

**Comment by blackfalcon** [comment]
I moved that to Sprint 12 as a top priority. It should be any day now. Sorry for any issues this may have caused.

**Comment by alaskaryan** [comment]
Please let me know as well when the disabled button is added...
