### ISSUE TITLE
Bundled output does not support IE11

### ISSUE THREAD

**Issue by znewton** [AlaskaAirlines/ods-button#61]
**Describe the bug**

The bundled output does not work in IE11

**To Reproduce**

1. Use the bundled output
2. Load in IE11

**Expected behavior**

Bundle does not include unsupported JS features like string template literals.

**Additional context**

Can be fixed by adding a browserslist
```
  "browserslist": [
    "last 3 chrome version",
    "last 3 firefox version",
    "last 3 edge version",
    "ie >= 11",
    "last 2 safari version"
  ],
```

**Comment by blackfalcon** [comment]
After review, sticking with the recommendation that was added to the WC-Generator project. 

```
  "browserslist": [
    "last 4 version",
    "> 1%",
    "IE 11"
  ],
```
