### ISSUE TITLE
Dotted focus outline appears when focusing in Firefox

### ISSUE THREAD

**Issue by geoffrey1218** [AlaskaAirlines/ods-button#76]
## Describe the bug
When I focus the button in Firefox, a dotted outline appears around the text in addition to the normal focus state. This does not happen in Chrome.

![image](https://user-images.githubusercontent.com/4992896/84959938-4c116900-b0b5-11ea-9143-7b3b3731a19c.png)

## To Reproduce
1. Render auro-button in Firefox
2. Focus the button using the keyboard.

## Expected behavior
The additional focus outline does not appear.

## Environment
OS: Windows 10
Browser: Firefox

**Comment by geoffrey1218** [comment]
I'll be submitting a PR for this one. Should be a one-line CSS fix.

**Comment by blackfalcon** [comment]
Yup, Firefox is choosing to be different

https://stackoverflow.com/questions/71074/how-to-remove-firefoxs-dotted-outline-on-buttons-as-well-as-links
